In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [92]:
gdf_1 = gpd.read_file('ALB_package/gadm41_ALB_1.json')
gdf_2 = gpd.read_file('ALB_package/gadm41_ALB_2.json')

In [44]:
poly = gpd.read_file('alb_adm_2019b_shp/alb_admbnda_adm2_2019c.shp')
admin_level = 2
if admin_level == 2:
    # poly['ADM1_PCODE'] = poly['ADM1_PCODE'].str.replace('0', '')
    # poly['ADM1_PCODE'] = poly['ADM1_PCODE'].str.replace('AL', 'ALB.')
    # poly['ADM1_PCODE'] = poly['ADM1_PCODE'] + '_1'
    poly['ADM1_HEAD'] = poly['ADM1_PCODE'].str[:2].str.replace('AL','ALB')
    poly['ADM1_PCODE'] = poly['ADM1_PCODE'].str[2:4]
    poly['ADM1_PCODE'] = poly['ADM1_PCODE'].astype(int).astype(str)
    poly['GID_1'] = poly['ADM1_HEAD'] + '.' + poly['ADM1_PCODE'] + '_1'

    poly['ADM2_TAIL'] = poly['ADM2_PCODE'].str[4:].str.replace('0', '')
    poly['ADM2_HEAD'] = poly['ADM2_PCODE'].str[:2].str.replace('AL','ALB.')
    poly['ADM2_PCODE'] = poly['ADM2_PCODE'].str[2:4]
    poly['ADM2_PCODE'] = poly['ADM2_PCODE'].astype(int).astype(str)
    poly['GID_2'] = poly['ADM2_HEAD'] + poly['ADM2_PCODE'] + '.' + poly['ADM2_TAIL'] + '_1'
    poly['ADM2_EN'] = poly['ADM2_EN'].str.replace('Bashkia ', '')
    poly = poly.rename({'ADM1_EN': 'NAME_1',
                        'ADM2_EN': 'NAME_2'}, axis=1)

poly = poly[['NAME_1', 'GID_1', 'NAME_2', 'GID_2']]
poly.head(60)

         NAME_1     GID_1              NAME_2       GID_2
0         Berat   ALB.1_1               Berat   ALB.1.1_1
1         Berat   ALB.1_1              Kucove   ALB.1.2_1
2         Berat   ALB.1_1             Polican   ALB.1.3_1
3         Berat   ALB.1_1             Skrapar   ALB.1.4_1
4         Berat   ALB.1_1       Ura Vajgurore   ALB.1.5_1
5         Diber   ALB.2_1             Bulqize   ALB.2.1_1
6         Diber   ALB.2_1               Diber   ALB.2.2_1
7         Diber   ALB.2_1                Klos   ALB.2.3_1
8         Diber   ALB.2_1                 Mat   ALB.2.4_1
9        Durres   ALB.3_1              Durres   ALB.3.1_1
10       Durres   ALB.3_1               Kruje   ALB.3.2_1
11       Durres   ALB.3_1              Shijak   ALB.3.3_1
12      Elbasan   ALB.4_1               Belsh   ALB.4.1_1
13      Elbasan   ALB.4_1              Cerrik   ALB.4.2_1
14      Elbasan   ALB.4_1             Elbasan   ALB.4.3_1
15      Elbasan   ALB.4_1              Gramsh   ALB.4.4_1
16      Elbasan   ALB.4_1            Librazhd   ALB.4.5_1
17      Elbasan   ALB.4_1               Peqin   ALB.4.6_1
18      Elbasan   ALB.4_1            Prrenjas   ALB.4.7_1
19         Fier   ALB.5_1             Divjake   ALB.5.1_1
20         Fier   ALB.5_1                Fier   ALB.5.2_1
21         Fier   ALB.5_1             Lushnje   ALB.5.3_1
22         Fier   ALB.5_1         Mallakaster   ALB.5.4_1
23         Fier   ALB.5_1               Patos   ALB.5.5_1
24         Fier   ALB.5_1            Roskovec   ALB.5.6_1
25  Gjirokaster   ALB.6_1             Dropull   ALB.6.1_1
26  Gjirokaster   ALB.6_1         Gjirokaster   ALB.6.2_1
27  Gjirokaster   ALB.6_1             Kelcyre   ALB.6.3_1
28  Gjirokaster   ALB.6_1            Libohove   ALB.6.4_1
29  Gjirokaster   ALB.6_1            Memaliaj   ALB.6.5_1
30  Gjirokaster   ALB.6_1              Permet   ALB.6.6_1
31  Gjirokaster   ALB.6_1            Tepelene   ALB.6.7_1
32        Korce   ALB.7_1              Devoll   ALB.7.1_1
33        Korce   ALB.7_1             Kolonje   ALB.7.2_1
34        Korce   ALB.7_1               Korce   ALB.7.3_1
35        Korce   ALB.7_1               Maliq   ALB.7.4_1
36        Korce   ALB.7_1            Pogradec   ALB.7.5_1
37        Korce   ALB.7_1              Pustec   ALB.7.6_1
38        Kukes   ALB.8_1               Krume   ALB.8.1_1
39        Kukes   ALB.8_1               Kukes   ALB.8.2_1
40        Kukes   ALB.8_1             Tropoje   ALB.8.3_1
41        Lezhe   ALB.9_1              Kurbin   ALB.9.1_1
42        Lezhe   ALB.9_1               Lezhe   ALB.9.2_1
43        Lezhe   ALB.9_1             Mirdite   ALB.9.3_1
44      Shkoder  ALB.10_1         Fushe Arrez  ALB.10.1_1
45      Shkoder  ALB.10_1      Malesi e Madhe  ALB.10.2_1
46      Shkoder  ALB.10_1                Puke  ALB.10.3_1
47      Shkoder  ALB.10_1             Shkoder  ALB.10.4_1
48      Shkoder  ALB.10_1           Vau Dejes  ALB.10.5_1
49       Tirane  ALB.11_1               Kamez  ALB.11.1_1
50       Tirane  ALB.11_1              Kavaje  ALB.11.2_1
51       Tirane  ALB.11_1          Rrogozhine  ALB.11.3_1
52       Tirane  ALB.11_1                Vore  ALB.11.4_1
53       Tirane  ALB.11_1  Tirana Municipally  ALB.11.5_1
54        Vlore  ALB.12_1             Delvine  ALB.12.1_1
55        Vlore  ALB.12_1               Finiq  ALB.12.2_1
56        Vlore  ALB.12_1              Himare  ALB.12.3_1
57        Vlore  ALB.12_1            Konispol  ALB.12.4_1
58        Vlore  ALB.12_1             Sarande  ALB.12.5_1
59        Vlore  ALB.12_1            Selenice  ALB.12.6_1

In [67]:
gdf_2[['NAME_1', 'GID_1', 'NAME_2', 'GID_2']].head(60)

         NAME_1     GID_1              NAME_2       GID_2
0         Berat   ALB.1_1               Berat   ALB.1.1_1
1         Berat   ALB.1_1              Kucove   ALB.1.2_1
2         Berat   ALB.1_1             Polican   ALB.1.3_1
3         Berat   ALB.1_1             Skrapar   ALB.1.4_1
4         Berat   ALB.1_1       Ura Vajgurore   ALB.1.5_1
5         Diber   ALB.2_1             Bulqize   ALB.2.1_1
6         Diber   ALB.2_1               Diber   ALB.2.2_1
7         Diber   ALB.2_1                Klos   ALB.2.3_1
8         Diber   ALB.2_1                 Mat   ALB.2.4_1
9        Durres   ALB.3_1              Durres   ALB.3.1_1
10       Durres   ALB.3_1               Kruje   ALB.3.2_1
11       Durres   ALB.3_1              Shijak   ALB.3.3_1
12      Elbasan   ALB.4_1               Belsh   ALB.4.1_1
13      Elbasan   ALB.4_1              Cerrik   ALB.4.2_1
14      Elbasan   ALB.4_1             Elbasan   ALB.4.3_1
15      Elbasan   ALB.4_1              Gramsh   ALB.4.4_1
16      Elbasan   ALB.4_1            Librazhd   ALB.4.5_1
17      Elbasan   ALB.4_1               Peqin   ALB.4.6_1
18      Elbasan   ALB.4_1            Prrenjas   ALB.4.7_1
19         Fier   ALB.5_1             Divjake   ALB.5.1_1
20         Fier   ALB.5_1                Fier   ALB.5.2_1
21         Fier   ALB.5_1             Lushnje   ALB.5.3_1
22         Fier   ALB.5_1         Mallakaster   ALB.5.4_1
23         Fier   ALB.5_1               Patos   ALB.5.5_1
24         Fier   ALB.5_1            Roskovec   ALB.5.6_1
25  Gjirokaster   ALB.6_1             Dropull   ALB.6.1_1
26  Gjirokaster   ALB.6_1         Gjirokaster   ALB.6.2_1
27  Gjirokaster   ALB.6_1             Kelcyre   ALB.6.3_1
28  Gjirokaster   ALB.6_1            Libohove   ALB.6.4_1
29  Gjirokaster   ALB.6_1            Memaliaj   ALB.6.5_1
30  Gjirokaster   ALB.6_1              Permet   ALB.6.6_1
31  Gjirokaster   ALB.6_1            Tepelene   ALB.6.7_1
32        Korce   ALB.7_1              Devoll   ALB.7.1_1
33        Korce   ALB.7_1             Kolonje   ALB.7.2_1
34        Korce   ALB.7_1               Korce   ALB.7.3_1
35        Korce   ALB.7_1               Maliq   ALB.7.4_1
36        Korce   ALB.7_1            Pogradec   ALB.7.5_1
37        Korce   ALB.7_1              Pustec   ALB.7.6_1
38        Kukes   ALB.8_1               Krume   ALB.8.1_1
39        Kukes   ALB.8_1               Kukes   ALB.8.2_1
40        Kukes   ALB.8_1             Tropoje   ALB.8.3_1
41        Lezhe   ALB.9_1              Kurbin   ALB.9.1_1
42        Lezhe   ALB.9_1               Lezhe   ALB.9.2_1
43        Lezhe   ALB.9_1             Mirdite   ALB.9.3_1
44      Shkoder  ALB.10_1         Fushe Arrez  ALB.10.1_1
45      Shkoder  ALB.10_1      Malesi e Madhe  ALB.10.2_1
46      Shkoder  ALB.10_1                Puke  ALB.10.3_1
47      Shkoder  ALB.10_1             Shkoder  ALB.10.4_1
48      Shkoder  ALB.10_1           Vau Dejes  ALB.10.5_1
49       Tirane  ALB.11_1               Kamez  ALB.11.1_1
50       Tirane  ALB.11_1              Kavaje  ALB.11.2_1
51       Tirane  ALB.11_1          Rrogozhine  ALB.11.3_1
52       Tirane  ALB.11_1                Vore  ALB.11.4_1
53       Tirane  ALB.11_1  Tirana Municipally  ALB.11.5_1
54        Vlore  ALB.12_1             Delvine  ALB.12.1_1
55        Vlore  ALB.12_1               Finiq  ALB.12.2_1
56        Vlore  ALB.12_1              Himare  ALB.12.3_1
57        Vlore  ALB.12_1            Konispol  ALB.12.4_1
58        Vlore  ALB.12_1             Sarande  ALB.12.5_1
59        Vlore  ALB.12_1            Selenice  ALB.12.6_1

In [90]:
full = pd.read_csv('D:\Work\WB\LDT\ALB_package\WB_GPBP_GED_ALB_2_full.csv')
full

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
C:\Users\sonle\AppData\Local\Temp\ipykernel_19376\4025953752.py:1: SyntaxWarning: invalid escape sequence '\W'
  full = pd.read_csv('D:\Work\WB\LDT\ALB_package\WB_GPBP_GED_ALB_2_full.csv')

,PROVINCE_ID,PROVINCE,DISTRICT_ID,DISTRICT,YEAR,LUMINOSITY,LUMINOSITY_PCT_CHANGE,BUILT_PCT,BUILT_COVER_GROWTH,UTIL_SCORE,...,TEMP_EXTREMELY_HOT_STD,TEMP_EXTREMELY_COLD_STD,TEMP_MAX_TEMP_STD,TEMP_PRECIPITATION_MAX_STD,TEMP_EXTREMELY_WET_STD,TEMP_EXTREMELY_DRY_STD,FOREST_GREEN_PCT_STD,FOREST_GREEN_COVER_GROWTH_STD,BUILT_BUILT_PCT_STD,BUILT_BUILT_COVER_GROWTH_STD
0,ALB.1_1,Berat,ALB.1.1_1,Berat,2019,21786.15,6.862299,7.015844,5.459367,77.05,...,0.644608,0.706136,0.580832,-0.546496,0.821969,-0.240274,0.307773,-0.190814,-0.138979,0.510461
1,ALB.1_1,Berat,ALB.1.1_1,Berat,2020,21320.60,2.084981,7.119555,1.478241,75.41,...,-0.149757,-0.319374,0.205684,-0.612367,0.466808,-0.784167,0.308966,0.038810,-0.130465,-0.238998
2,ALB.1_1,Berat,ALB.1.1_1,Berat,2021,25300.10,-0.420318,7.312289,2.707104,77.05,...,0.351722,-0.439736,0.595632,-0.543051,0.416458,-0.308215,0.292262,-0.099463,-0.114643,-0.007661
3,ALB.1_1,Berat,ALB.1.1_1,Berat,2022,34395.15,-2.945870,7.564294,3.446326,80.33,...,0.058837,0.578817,0.269446,-0.568639,0.461514,-0.579975,0.276156,-0.095140,-0.093955,0.131500
4,ALB.1_1,Berat,ALB.1.2_1,Kucove,2019,12328.65,12.848910,13.687034,8.584345,63.93,...,0.351722,0.833456,0.790727,-0.868950,1.122347,-0.444095,-0.279183,-0.556260,0.408677,1.098748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,ALB.9_1,Lezhe,ALB.9.2_1,Lezhe,2022,33016.30,11.299304,11.979856,-1.948278,78.69,...,0.254094,0.960775,0.121471,0.427326,-0.259394,-0.647915,-0.312102,0.203408,0.268530,-0.884051
240,ALB.9_1,Lezhe,ALB.9.3_1,Mirdite,2019,5733.90,3.952699,1.578150,-4.141692,42.62,...,0.546979,0.960775,0.484097,1.013170,-0.649887,1.254409,0.718323,0.192115,-0.585374,-1.296968
241,ALB.9_1,Lezhe,ALB.9.3_1,Mirdite,2020,6557.80,-4.405473,1.591791,0.864366,45.90,...,0.142328,-0.954231,0.009754,0.892190,-0.971070,0.164396,0.708203,-0.044435,-0.584255,-0.354562
242,ALB.9_1,Lezhe,ALB.9.3_1,Mirdite,2021,7005.15,19.396238,1.762217,10.706561,47.54,...,0.058837,0.578817,0.294838,1.065455,-0.755019,0.914708,0.709844,0.041611,-0.570264,1.498262
243,ALB.9_1,Lezhe,ALB.9.3_1,Mirdite,2022,7967.30,19.629817,1.782667,1.160494,47.54,...,0.156465,0.833456,0.199903,0.925654,-0.664906,1.322349,0.710938,0.037602,-0.568585,-0.298815

In [83]:
full['PROVINCE_ID'].value_counts().to_frame().reset_index().sort_values(by=['PROVINCE_ID'])

   PROVINCE_ID  count
6     ALB.10_1     20
7     ALB.11_1     20
0     ALB.12_1     28
5      ALB.1_1     20
8      ALB.2_1     16
9      ALB.3_1     12
1      ALB.4_1     28
3      ALB.5_1     24
2      ALB.6_1     28
4      ALB.7_1     24
10     ALB.8_1     12
11     ALB.9_1     12

In [77]:
dist = full['DISTRICT_ID'].value_counts().to_frame().reset_index()
dist = dist.sort_values(by=['DISTRICT_ID'])
dist.head(60)

   DISTRICT_ID  count
0    ALB.1.1_1      4
31   ALB.1.2_1      4
33   ALB.1.3_1      4
34   ALB.1.4_1      4
35   ALB.1.5_1      4
36  ALB.10.1_1      4
37  ALB.10.2_1      4
38  ALB.10.3_1      4
39  ALB.10.4_1      4
40  ALB.10.5_1      4
41  ALB.11.1_1      4
42  ALB.11.2_1      4
43  ALB.11.3_1      4
44  ALB.11.4_1      4
45  ALB.11.5_1      4
46  ALB.12.1_1      4
47  ALB.12.2_1      4
48  ALB.12.3_1      4
49  ALB.12.4_1      4
50  ALB.12.5_1      4
51  ALB.12.6_1      4
52  ALB.12.7_1      4
53   ALB.2.1_1      4
54   ALB.2.2_1      4
55   ALB.2.3_1      4
56   ALB.2.4_1      4
57   ALB.3.1_1      4
58   ALB.3.2_1      4
59   ALB.3.3_1      4
32   ALB.4.1_1      4
30   ALB.4.2_1      4
1    ALB.4.3_1      4
29   ALB.4.4_1      4
2    ALB.4.5_1      4
3    ALB.4.6_1      4
4    ALB.4.7_1      4
5    ALB.5.1_1      4
6    ALB.5.2_1      4
7    ALB.5.3_1      4
8    ALB.5.4_1      4
9    ALB.5.5_1      4
10   ALB.5.6_1      4
11   ALB.6.1_1      4
12   ALB.6.2_1      4
13   ALB.6.3_1      4
14   ALB.6.4_1      4
15   ALB.6.5_1      4
16   ALB.6.6_1      4
17   ALB.6.7_1      4
18   ALB.7.1_1      4
19   ALB.7.2_1      4
20   ALB.7.3_1      4
21   ALB.7.4_1      4
22   ALB.7.5_1      4
23   ALB.7.6_1      4
24   ALB.8.1_1      4
25   ALB.8.2_1      4
26   ALB.8.3_1      4
27   ALB.9.1_1      4
28   ALB.9.2_1      4

In [91]:
full['PROVINCE_ID'].value_counts() / 4

PROVINCE_ID
ALB.12_1    7.0
ALB.4_1     7.0
ALB.6_1     7.0
ALB.5_1     6.0
ALB.7_1     6.0
ALB.1_1     5.0
ALB.10_1    5.0
ALB.11_1    5.0
ALB.2_1     4.0
ALB.3_1     3.0
ALB.8_1     3.0
ALB.9_1     3.0
Name: count, dtype: float64

In [12]:
colnames=['radio', 'Mobilecountrycode',	'Mobilenetworkcode', 'area','cellID', 'unit', 'lon', 'lat',
	      'range', 'samples', 'changeable', 'created', 	'updated', 'averageSignal'] 
df = pd.read_csv('D:\Work\WB\LDT/test.csv.gz', compression='gzip', sep=',', names=colnames)
df

<>:3: SyntaxWarning: invalid escape sequence '\W'
<>:3: SyntaxWarning: invalid escape sequence '\W'
C:\Users\sonle\AppData\Local\Temp\ipykernel_27560\259051968.py:3: SyntaxWarning: invalid escape sequence '\W'
  df = pd.read_csv('D:\Work\WB\LDT/test.csv.gz', compression='gzip', sep=',', names=colnames)

,radio,Mobilecountrycode,Mobilenetworkcode,area,cellID,unit,lon,lat,range,samples,changeable,created,updated,averageSignal
0,GSM,220,5,256,22604,0,19.7992,45.3132,8260,72,1,1349276251,1711172248,0
1,GSM,220,1,22221,46841,0,19.2901,45.0389,15280,44,1,1350302540,1716816182,0
2,GSM,220,1,22221,46842,0,19.2197,45.0671,15518,45,1,1350302540,1716816242,0
3,GSM,220,1,22221,46782,0,19.3353,45.0455,11155,24,1,1350302540,1689592867,0
4,GSM,220,1,22221,46173,0,19.2074,45.0558,8567,10,1,1350302540,1689591737,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6981,UMTS,220,3,29999,6541073,0,21.5840,43.2340,1000,2,1,1719766624,1719826085,0
6982,UMTS,220,3,29999,6511068,0,21.5840,43.2340,1000,1,1,1719766811,1719766811,0
6983,UMTS,220,3,29999,6551073,0,21.5840,43.2340,1000,1,1,1719766827,1719766827,0
6984,UMTS,220,3,29999,6521086,0,21.5840,43.2340,1000,5,1,1719796405,1719828304,0
6985,UMTS,220,5,320,1340148,0,20.1327,44.8743,1000,1,1,1719838945,1719838945,0